<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <packaging>pom</packaging>
    <groupId>cchesser.javaperf</groupId>
    <artifactId>java-perf-workshop-parent</artifactId>
    <version>2.0-SNAPSHOT</version>
    <name>${project.artifactId}</name>
    <inceptionYear>2015</inceptionYear>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <maven.build.timestamp.format>yyyy-MM-dd</maven.build.timestamp.format>
        <!-- Workaround for http://jira.codehaus.org/browse/MRESOURCES-99 -->
        <buildTimestamp>${maven.build.timestamp}</buildTimestamp>
        <dropwizard.version>2.1.10</dropwizard.version>
        <metrics.version>4.2.38</metrics.version>
        <jackson.version>2.18.3</jackson.version>
        <jackson.databind.version>2.18.3</jackson.databind.version>
        <!-- scm info -->
        <scm.connection>scm:git:git://github.com:cchesser/java-perf-workshop.git</scm.connection>
        <scm.developerConnection>scm:git:git@github.com:cchesser/java-perf-workshop.git</scm.developerConnection>
        <scm.url>http://github.com/cchesser/java-perf-workshop</scm.url>

        <!-- tester dependencies -->
        <gatling.version>3.14.9</gatling.version>
        <scala.version>2.13.17</scala.version>

        <!-- java-heap-mcp dependencies -->
        <eclipse.platform.version>3.31.0</eclipse.platform.version>
        <eclipse.core.resources.version>3.22.0</eclipse.core.resources.version>
        <eclipse.core.commands.version>3.12.0</eclipse.core.commands.version>
        <icu4j.version>76.1</icu4j.version>
        <junit.version>5.12.2</junit.version>
        <assertj.version>3.27.3</assertj.version>
        <calcite.version>1.41.0</calcite.version>
        <janino.version>3.1.12</janino.version>
        <mat.distribution>1.16.1.202501091339</mat.distribution>
        <mcp.sdk.version>1.1.4</mcp.sdk.version>

        <!-- plugin versions -->
            <scala-maven-plugin.version>4.7.1</scala-maven-plugin.version>
        <gatling-maven-plugin.version>4.20.16</gatling-maven-plugin.version>
    </properties>
    <scm>
        <connection>${scm.connection}</connection>
        <developerConnection>${scm.developerConnection}</developerConnection>
        <url>${scm.url}</url>
        <tag>HEAD</tag>
    </scm>
    <developers>
        <developer>
            <id>cchesser</id>
            <name>Carl Chesser</name>
            <email>cchesser@gmail.com</email>
            <url>http://github.com/cchesser</url>
            <roles>
                <role>developer</role>
            </roles>
            <timezone>-6</timezone>
        </developer>
        <developer>
          <id>AnEmortalKid</id>
          <name>Jan Monterrubio</name>
          <email>janmonterrubio@gmail.com</email>
          <url>http://github.com/anemortalkid</url>
          <roles>
            <role>developer</role>
          </roles>
        </developer>
    </developers>
    <modules>
        <module>java-perf-workshop-server</module>
        <module>java-perf-workshop-tester</module>
        <module>java-heap-mcp</module>
  </modules>
    <dependencyManagement>
        <dependencies>
            <dependency>
              <groupId>com.github.tomakehurst</groupId>
              <artifactId>wiremock-jre8</artifactId>
              <version>2.35.2</version>
            </dependency>
            <dependency>
                <groupId>io.dropwizard.metrics</groupId>
                <artifactId>metrics-annotation</artifactId>
                <version>${metrics.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-annotations</artifactId>
                <version>${jackson.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-databind</artifactId>
                <version>${jackson.databind.version}</version>
            </dependency>
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>33.5.0-jre</version>
            </dependency>
            <dependency>
                <groupId>io.dropwizard</groupId>
                <artifactId>dropwizard-core</artifactId>
                <version>${dropwizard.version}</version>
            </dependency>
            <dependency>
                <groupId>io.dropwizard</groupId>
                <artifactId>dropwizard-jersey</artifactId>
                <version>${dropwizard.version}</version>
            </dependency>
            <dependency>
                <groupId>javax.validation</groupId>
                <artifactId>validation-api</artifactId>
                <version>1.1.0.Final</version>
            </dependency>
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-api</artifactId>
                <version>1.7.12</version>
            </dependency>
            <dependency>
                <groupId>javax.ws.rs</groupId>
                <artifactId>javax.ws.rs-api</artifactId>
                <version>2.1.1</version>
            </dependency>
            <dependency>
                <groupId>junit</groupId>
                <artifactId>junit-dep</artifactId>
                <version>4.11</version>
            </dependency>
            <dependency>
                <groupId>io.gatling</groupId>
                <artifactId>gatling-app</artifactId>
                <version>${gatling.version}</version>
            </dependency>
            <dependency>
                <groupId>io.gatling</groupId>
                <artifactId>gatling-recorder</artifactId>
                <version>${gatling.version}</version>
            </dependency>
            <dependency>
                <groupId>io.gatling.highcharts</groupId>
                <artifactId>gatling-charts-highcharts</artifactId>
                <version>${gatling.version}</version>
            </dependency>
            <dependency>
                <groupId>org.scala-lang</groupId>
                <artifactId>scala-library</artifactId>
                <version>${scala.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.datatype</groupId>
                <artifactId>jackson-datatype-jsr310</artifactId>
                <version>${jackson.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.platform</groupId>
                <artifactId>org.eclipse.core.runtime</artifactId>
                <version>${eclipse.platform.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.platform</groupId>
                <artifactId>org.eclipse.core.resources</artifactId>
                <version>${eclipse.core.resources.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.platform</groupId>
                <artifactId>org.eclipse.core.commands</artifactId>
                <version>${eclipse.core.commands.version}</version>
            </dependency>
            <dependency>
                <groupId>com.ibm.icu</groupId>
                <artifactId>icu4j</artifactId>
                <version>${icu4j.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.calcite</groupId>
                <artifactId>calcite-core</artifactId>
                <version>${calcite.version}</version>
            </dependency>
            <dependency>
                <groupId>org.codehaus.janino</groupId>
                <artifactId>janino</artifactId>
                <version>${janino.version}</version>
            </dependency>
            <dependency>
                <groupId>org.codehaus.janino</groupId>
                <artifactId>commons-compiler</artifactId>
                <version>${janino.version}</version>
            </dependency>
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter</artifactId>
                <version>${junit.version}</version>
            </dependency>
            <dependency>
                <groupId>org.assertj</groupId>
                <artifactId>assertj-core</artifactId>
                <version>${assertj.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <build>
      <pluginManagement>
        <plugins>
          <plugin>
              <groupId>org.apache.maven.plugins</groupId>
              <artifactId>maven-compiler-plugin</artifactId>
              <version>3.14.0</version>
          </plugin>
          <plugin>
              <groupId>io.gatling</groupId>
              <artifactId>gatling-maven-plugin</artifactId>
              <version>${gatling-maven-plugin.version}</version>
          </plugin>
          <plugin>
              <groupId>net.alchim31.maven</groupId>
              <artifactId>scala-maven-plugin</artifactId>
              <version>${scala-maven-plugin.version}</version>
          </plugin>
        </plugins>
      </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <showDeprecation>true</showDeprecation>
                    <showWarnings>true</showWarnings>
                    <source>25</source>
                    <target>25</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
