val list = List(
  "Soft-Skills",
  "joke",
  "Evolving",
  "Agile",
  "DataGovernance",
  "InformationGovernance",
  "Data",
  "Big Data",
  "angularjs",
  "javascript",
  "js",
  "solid",
  "azure",
  "microservice",
  "spring",
  "docker",
  "linq",
  "jvm",
  "casper",
  "apache",
  "api",
  "nodejs",
  "react",
  "Microsoft-Azure",
  "Visual-Studio",
  ".Net-Framework",
  "Cloud-Design-Patterns",
  "Workflow",
  "sql",
  "web design",
  "design",
  "css",
  "leader",
  "CQRS",
  "domain driven design",
  "Functional programming",
  "chef",
  "Clean Code",
  "refactoring",
  "devops",
  "distributed systems",
  "Enterprise Architecture",
  "Actor Model",
  "Akka",
  "scala",
  "F#",
  "elixir",
  "erlang",
  "functional-programming",
  "functional",
  "FizzBuzz",
  "Full Stack",
  "Performance",
  "CRUD",
  "Chrome Extensions",
  "Reactive",
  "Grails",
  "ruby",
  "go",
  "Groovy",
  "Profiling",
  "Arduino",
  "Raspberry-Pi",
  "intel-galileo",
  "net-duino",
  "Azure-Stream-Analytics",
  "Aurelia",
  "MeteorJS",
  "ORM",
  "ElasticSearch",
  "Kibana",
  "Logstash",
  "Swift",
  "ios",
  "REST",
  "Flux",
  "Knockout",
  "Backbone",
  "Ember",
  "Meteor",
  "Meteor.js",
  "JavaScript",
  "Node",
  "Node.js",
  "SPA",
  "Swagger",
  "Systems-Thinking",
  "Senge",
  "Deming",
  "Learning",
  "Learning-Organizations",
  "Lean",
  "security",
  "hacking",
  "cookies",
  "sessions",
  "mvc",
  "TypeScript",
  "Front-end",
  "UX",
  "Gulp",
  "Slush",
  "Unit Testing",
  "xamarin",
  "mobile",
  "Chromecast"
)

list.map(item => s"""{ "searchTerm":"${item}" }""").mkString(",")


